### PR TITLE
to trace calling C functions

### PR DESCRIPTION
**Pull request by kakkun61**
`cabal build -fdebug` makes debug tracing active.

### CODE REVIEW

**Comment by ryantm** [comment]
@kakkun61 The changes look fine to me. Why do you want debugging like this? Did you do any performance bechmarks?

**Comment by kakkun61** [comment]
@ryantm While I developed an app with HDBC-mysql, I got an error message “[Commands out of sync; you can't run this command now](https://dev.mysql.com/doc/refman/5.6/en/commands-out-of-sync.html)” raised by libmysqlclient.
And so for debugging I want to know which C functions are called and that the call order.

**Comment by ryantm** [comment]
Thanks. I tested it; merged it; made a release http://hackage.haskell.org/package/HDBC-mysql-0.7.1.0 . Please note, I as not able to use `cabal build -fdebug`. It seems like the flags are not available for build, but they are for install. Is that the case for you too?

**Comment by kakkun61** [comment]
Sorry, I actually tested `cabal build -fdebug`, I used `stack build --flag HDBC-mysql:debug`.

**Pull request merged**
